name: Run pre-commit hook on push
on:
  push:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Replace with the version of Python you need
      - name: Run pre-commit hook
        run: |
          bash .hooks/pre-commit
